/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mypackage; 

/**
 *
 * @author kenne
 */
public class LogInPanel extends javax.swing.JPanel {

    javax.swing.JFrame frame;
    
    public LogInPanel(javax.swing.JFrame frame) {
        this.frame = frame;
        initComponents();
        frame.getRootPane().setDefaultButton(logInbutton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logintitle1 = new javax.swing.JLabel();
        logintitle2 = new javax.swing.JLabel();
        userfield = new javax.swing.JTextField();
        userlabel = new javax.swing.JLabel();
        passlabel = new javax.swing.JLabel();
        passfield = new javax.swing.JPasswordField();
        logInbutton = new javax.swing.JButton();
        registerbutton = new javax.swing.JButton();
        showpassCheckBox = new javax.swing.JCheckBox();

        setPreferredSize(new java.awt.Dimension(320, 500));
        setBackground(new java.awt.Color(238, 238, 238));

        logintitle1.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        logintitle1.setForeground(new java.awt.Color(55, 58, 64));
        logintitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logintitle1.setText("Log In");
        logintitle1.setToolTipText("Log In");

        logintitle2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        logintitle2.setForeground(new java.awt.Color(104, 109, 118));
        logintitle2.setText("to calculator");

        userfield.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        userfield.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        userfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userfieldActionPerformed(evt);
            }
        });

        userlabel.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        userlabel.setForeground(new java.awt.Color(55, 58, 64));
        userlabel.setText("Username:");

        passlabel.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        passlabel.setForeground(new java.awt.Color(55, 58, 64));
        passlabel.setText("Password:");

        passfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        logInbutton.setBackground(new java.awt.Color(220, 95, 0));
        logInbutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        logInbutton.setForeground(new java.awt.Color(238, 238, 238));
        logInbutton.setText("Log In");
        logInbutton.setFocusable(false);
        logInbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInbuttonActionPerformed(evt);
            }
        });

        registerbutton.setBackground(new java.awt.Color(104, 109, 118));
        registerbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerbutton.setForeground(new java.awt.Color(238, 238, 238));
        registerbutton.setText("Register");
        registerbutton.setFocusable(false);
        registerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbuttonActionPerformed(evt);
            }
        });

        showpassCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        showpassCheckBox.setForeground(new java.awt.Color(104, 109, 118));
        showpassCheckBox.setText("show password");
        showpassCheckBox.setFocusable(false);
        showpassCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logintitle2)
                    .addComponent(logintitle1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passlabel)
                            .addComponent(userlabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(logInbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(registerbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(userfield)
                                .addComponent(passfield, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(showpassCheckBox, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(logintitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logintitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userlabel))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showpassCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logInbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerbutton)
                .addContainerGap(144, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userfieldActionPerformed
    }//GEN-LAST:event_userfieldActionPerformed

    private void logInbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInbuttonActionPerformed
        accounts = ops.readFile();

        String username = userfield.getText(); // Get text from username field
        String password = new String(passfield.getPassword()); // Get password as String

        if (accounts.containsKey(username)) {
            if (accounts.get(username).equals(password)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Login successful!");
                frame.setContentPane(new CalculatorPanel(frame));
                frame.revalidate();
            } else {
                passfield.setText("");
                javax.swing.JOptionPane.showMessageDialog(this, "Incorrect Password", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else {
            userfield.setText("");
            passfield.setText("");
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid username or password.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_logInbuttonActionPerformed

    private void registerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbuttonActionPerformed
        frame.setContentPane(new RegisterPanel(frame));
        frame.revalidate();
    }//GEN-LAST:event_registerbuttonActionPerformed

    private void showpassCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassCheckBoxActionPerformed
        if (showpassCheckBox.isSelected()) {
            passfield.setEchoChar((char)0);
        } else {
            passfield.setEchoChar('*');
        }
    }//GEN-LAST:event_showpassCheckBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton logInbutton;
    private javax.swing.JLabel logintitle1;
    private javax.swing.JLabel logintitle2;
    private javax.swing.JPasswordField passfield;
    private javax.swing.JLabel passlabel;
    private javax.swing.JButton registerbutton;
    private javax.swing.JCheckBox showpassCheckBox;
    private javax.swing.JTextField userfield;
    private javax.swing.JLabel userlabel;
    // End of variables declaration//GEN-END:variables

    private static java.util.HashMap<String, String> accounts;
    private static FileOps ops = new FileOps();
}
